name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Dependencies
      run: |
        echo "Installing dependencies..."

    - name: Build Application
      run: |
        echo "Building the application..."

    - name: Run Tests
      run: |
        echo "Running tests..."

    - name: Deploy Application
      if: success()
      run: |
        echo "Deploying to production..."
